### ISSUE TITLE
Lucene directory not found error

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock-v8-Alpha-Issues#1]
I enabled the Lucene universal search type and disabled the elastic search type, then re-enabled universal search as an available search service.
Reloading the internal home page, I searched for a name which I know is both a last name and a group name, but no autofill suggestions were offered. I pressed enter to go to the search results page, and got an exception:

DirectoryNotFoundException in Lucene.Net

Message
directory 'C:\rockalpha\App_Data\LuceneSearchIndex' does not exist

Presumably there is more to set up for this search as there was for elastic search. Should a note to this effect be added to the Lucene configuration?

**Comment by edmistj** [comment]
Can you manually create the directory and continue testing. We’ll get that code to create the directory if it doesn’t exist.

**Comment by GerhardPowell** [comment]
Now it will create a folder if it does not exists

**Comment by mikejed** [comment]
This is the first I've been able to get back in and test again. At some point, it looks like the folder was auto-created, and universal search does work now. However, it doesn't appear to return groups in the list of results. If I search a group, it will auto-complete with a list of people in that group, but the group entity itself is not in the list.

Can you confirm for me that groups should be in the list of results?

**Comment by GerhardPowell** [comment]
var groups = new GroupService( rockContext ).Queryable().AsNoTracking()
                                .Where( g =>
                                     g.IsActive == true
                                     && g.GroupType.IsIndexEnabled == true );
returns no groups

**Comment by GerhardPowell** [comment]
var contentChannelItems = new ContentChannelItemService( rockContext ).Queryable()
                                            .Where( i =>
                                                i.ContentChannel.IsIndexEnabled
                                                && ( i.ContentChannel.RequiresApproval == false || i.ContentChannel.ContentChannelType.DisableStatus || i.Status == ContentChannelItemStatus.Approved ) );

returns no contentchannels

**Comment by GerhardPowell** [comment]
Home > General Settings > Group Types
Select a group type.
General, Select 'Enable Indexing'
Click save

**Comment by mikejed** [comment]
Thank you, that was the step I was missing. Checking that box and then reindexing the groups was all it took for the groups to show up in the search results. _Sometimes it's the little things when you've done it before and it's *mostly* already done_

**Comment by GerhardPowell** [comment]
I bet almost everyone will get caught out by this. I will let Amy know so that she can add it to the documentation.

**Comment by mikejed** [comment]
It's mostly already there:
https://www.rockrms.com/Rock/BookContent/32/120#group
But doesn't specifically call out the `Enable Indexing` checkbox. That's probably all that's needed. I just didn't go back through _everything_ (my mistake) since I thought it was still configured from when we were trying out elasticsearch

**Comment by edmistj** [comment]
Please don’t take any action with Amy.

On Jun 27, 2018, at 4:58 PM, Gerhard Powell <notifications@github.com<mailto:notifications@github.com>> wrote:


I bet almost everyone will get caught out by this. I will let Amy know so that she can add it to the documentation.
