### ISSUE TITLE
Communication Wizard Keeps Subject of First Template Chosen

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock-v8-Alpha-Issues#10]
1. Start a new communication and choose a template that has a _predefined_ subject.
2. Click Next to move to next step in wizard.
3. Click Previous because you realized you chose the wrong template.
4. Now choose a different template with NO predefined subject.
5. Click Next and observe the _Email Subject_ field still has the subject of the first template that was selected.

While obviously not a huge deal to just edit the subject, the possibility of it going unnoticed and an email being sent with an off-topic subject is real.

**Comment by MikeDPeterson** [comment]
fixed with https://github.com/SparkDevNetwork/Rock/commit/ddf9ae1bdf39286b992c5c924c7d71ab26e5d0a9
