### ISSUE TITLE
Pending Communication Weirdness

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock-v8-Alpha-Issues#11]
This one is hard to describe, but I'll try. 

1. Send a new communication that exceeds the threshold for approval, to force it into "needs approval" mode.
2. As a communications approver/admin, go to People | Communication History and observe that the pending communication does not show up in the list (and assuming you have no filters enabled). 
3. Filter specifically for _Pending Approval_ status and observe the pending communication now appears in the list. Is that working as designed? If so, fine (though it seems it should show ALL communications if no filters are set)... but here's the weird part:

- On Firefox, clicking the _Filter Options_ on communications history briefly shows the filter panel, then you end up within the most recent communication in the list, as if you clicked on that item. There's no way to get to Filter Options (on Firefox.. Chrome works fine) in this state. But the real kicker is that this ONLY happens if there is a pending communication in the list, even if that communication isn't showing (because with no filters set the pending item does not show). If there is NO pending item, Firefox shows the Filter Options just fine. 

Here's an example of using Firefox to click on the Filter Options, with a (hidden, because no filters are set) pending communication in the list. You can see that when I click Filter Options, instead of getting to the options panel I end up IN the prior (most recent) sent item, which is the Pending Communication alert that went out to Comms Admin role.. 
![comm_history](https://user-images.githubusercontent.com/3903408/42110880-49ecf098-7ba8-11e8-8f82-cbcef2992402.gif)

**Comment by JimMichael** [comment]
So when you had no filter, you saw pending comms? I'm on same version of FF and Win here and I get what you see above, so I guess if no one else can dupe we'll call it "spooky action at a distance" and you can close.

**Comment by cabal95** [comment]
I wasn't able to replicate either problem on my box.

I can't get it to be truly "no filter" as it seems to require a Created Date Range (probably good idea) that defaults to 1 week ago. But with as much of the filter blanked out as possible, upon loading the page I see the pending communication.

On Firefox 61.0.1 64-bit, Win 10; Firefox works fine with the filter options. Is it possible you have some HTML block or other block with javascript that might be triggering a postback when you expand the filter options?

**Comment by ethan-sparkdevnetwork** [comment]
Closing.
