### ISSUE TITLE
Cannot set page Context Parameter Names

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock-v8-Alpha-Issues#14]
When I try to edit a page with a context aware block on it, I can type stuff into the text box for the parameter name, but when I click Save and go back in to verify that it took (since the block still wasn't showing anything) the field is blank again.

![image](https://user-images.githubusercontent.com/1119863/42139464-5f82014a-7d43-11e8-9bdf-9a7f66f74447.png)

**Comment by cabal95** [comment]
Okay, actually looks like this is a cache issue. Since I needed this to test something else I went into the database to add manually and noticed it was already there. Clearing Cache in Rock made it show up in the UI and the block picked it up instantly too.

**Comment by MikeDPeterson** [comment]
fixed with https://github.com/SparkDevNetwork/Rock/commit/39e3e3e5871f5783eb5aa5ec85f9481547174e8e
