### ISSUE TITLE
Note Reply Depth check in Lava is off by one

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock-v8-Alpha-Issues#15]
I setup a note with a max reply depth of 1. That should mean the original note plus one level deep of replies.

The stock Lava allowed for the original note, plus a reply, plus a reply to that reply (2 levels deep of replies).

Changing the following line to `>=` seems to fix the problem:

https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Assets/Lava/NoteViewItem.lava#L37

**Comment by garrettjohnson** [comment]
Fixed via https://github.com/SparkDevNetwork/Rock/commit/6ca613ae62f23c48d9a79ae45d59dcfd85eba71d
