### ISSUE TITLE
NoteWatch.WatchReplies does not appear to be used

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock-v8-Alpha-Issues#16]
I can't find any place this field is actually used.  Based on the name I would assume it's meant to indicate that the entire descendant tree of notes should be watched.

When `IsWatching` is set to true, then only first-level child notes will have notifications sent. So if a reply to a reply is posted, no notification will be sent unless you also watch that reply.

When `WatchReplies` is set to true, *I would assume* that a reply to a reply would have a notification sent as well.  And also replies to replies to replies to.. etc.

**Comment by edmistj** [comment]
We didn't implement this yet. We felt that watching all levels of replies was too much. We may come back to this though at a later date.
