### ISSUE TITLE
Minor Job List formatting issue

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock-v8-Alpha-Issues#17]
Rock v7 jobs list header looks like this:
![image](https://user-images.githubusercontent.com/3903408/42174750-f2a0e1da-7de8-11e8-8121-342cf376ca59.png)

v8 looks like this (uneven vertical formatting)
![image](https://user-images.githubusercontent.com/3903408/42174784-07ac7cf6-7de9-11e8-8ac5-536b3d2312c0.png)

**Comment by garrettjohnson** [comment]
Fixed via https://github.com/SparkDevNetwork/Rock/commit/a628d4621f0eb52f9927215cf6208ec69911ec5f
