### ISSUE TITLE
Note Entry textbox always shows focus ring

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock-v8-Alpha-Issues#19]
It seems like the new layout of the Note Entry box has a glitched UI, in that it always shows the focus ring around it. It's possible this was intentional, but I don't think it was.

If turn off the "always on" border color, and manually toggle the `:focus` class then it highlights and de-highlights like one would expect. The problem, I think, is that the `:focus` class is applied to the parent div - which never actually gets focus.

**As it looks now, without focus**

![image](https://user-images.githubusercontent.com/1119863/42176338-7ac20f32-7ddd-11e8-837f-826c244c23aa.png)

**As it look snow, with focus**

![image](https://user-images.githubusercontent.com/1119863/42176353-884c85f6-7ddd-11e8-9fb1-d063ae9c08bb.png)

**As I think maybe it's supposed to look without focus**

![image](https://user-images.githubusercontent.com/1119863/42176403-add373d4-7ddd-11e8-9e02-7079eacdf5cc.png)

**Showing the `:focus` class manually enabled**

![image](https://user-images.githubusercontent.com/1119863/42176454-d8226910-7ddd-11e8-8307-c5b778db7943.png)

As you can see in this last screenshot, the `.note-editor .meta-body:focus` pseudo class would apply the focus state - however that just doesn't happen normally because the `div` doesn't have the focus, the `textarea` does.  Either way, though, the `.note-editor .meta-body` class is applying the focus ring no matter what.

Since we are trying to put a focus ring around the whole thing and not just the single focused control, maybe we have to use javascript or something to apply a pseudo focus class to the .meta-body onFocus() and remove it onBlur() ?

Also, testing done in FireFox Windows 61.0 (64-bit)

**Comment by garrettjohnson** [comment]
Fixed via https://github.com/SparkDevNetwork/Rock/commit/2b1eb14f2e6e47c7aa044d20fb9bba2f52ee299b (Added a focus-within polyfill for older browsers)

Unfocused state
![image](https://user-images.githubusercontent.com/374209/42182997-0971bfcc-7df5-11e8-8b8f-6448e3f68e74.png)

Focused State
![image](https://user-images.githubusercontent.com/374209/42183017-1ca928be-7df5-11e8-8653-e6d80b2ea3b0.png)
