### ISSUE TITLE
Homepage Metrics display demo data on installation

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock-v8-Alpha-Issues#2]
When I upgraded our server to v8, I was confused by the metrics displayed on the internal homepage. I recommend that, rather than populating these metrics with fake data, they should instead be run once so they return accurate data. Is that possible?

**Comment by edmistj** [comment]
Please update to not show incorrect data, but run the actual SQL in the migration.

**Comment by GerhardPowell** [comment]
I have added a migration to update the initial values to the actual values

**Comment by mikejed** [comment]
Having just installed alpha2, our `Active Connection Requests` section indicates that we have 6058 requests, and our `Active Families` section indicates that we have 0 active families. In fact these numbers should be reversed.

**Comment by nairdo** [comment]
Gerhard's fix (https://github.com/SparkDevNetwork/Rock/commit/0f68354fb840d743f3c9771fa1c38128933eaf1d) is actually to an existing 1.8.0 migration so even v8.0 beta testers will have the correction.
