### ISSUE TITLE
Exception when clearing filters on a group grid that contains attributes

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock-v8-Alpha-Issues#20]
Clearing the filters on a group in Group Viewer throws an error. I was able to dupe on prealpha.

1. Go to People | Group Viewer | Ushers
2. Click Filter Options, click Clear Filter, then click Apply Filter.
3. Exception occurs.

Note that this is not a unique case of clearing empty filters or similar. I discovered it when I HAD filtered on a group attribute, then tried to clear that filter. This also does not seem to happen on any groups that don't contain group member attributes.
![image](https://user-images.githubusercontent.com/3903408/42239940-38b664f0-7ecb-11e8-9bc8-b4451388fba7.png)

![image](https://user-images.githubusercontent.com/3903408/42239947-42713704-7ecb-11e8-8329-bcf96d72730c.png)

**Comment by ethan-sparkdevnetwork** [comment]
Fixed in ea3d78e7.
