### ISSUE TITLE
Person Attributes list is not sorted and columns are not sortable.

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock-v8-Alpha-Issues#21]
The list on `Admin | General | Person Attributes` used to be sorted alphabetically by Name (by default), and allowed clicking the Id or Name column to sort by Id, or by Z-A, etc. This is no longer possible in v8.

**Comment by shivambareria** [comment]
@edmistj  Ordering was added to the block, but because of that now sorting is not possible.

**Comment by JimMichael** [comment]
I don't understand this response. I don't see any setting in the block to sort the items, and they are currently presented in an unreasonable order.

**Comment by edmistj** [comment]
Because the list is now orderable, it can't be sortable. 

![image](https://user-images.githubusercontent.com/548178/42385039-8bb0e302-80f0-11e8-801f-6eca4df45324.png)

**Comment by JimMichael** [comment]
Ah, ok! I wouldn’t have made that trade off (dealing with hundreds of attributes randomly ordered is a pain now), but st least I understand the issue.

**Comment by edmistj** [comment]
Yeah I get the trade-off, but there wasn't a way to change the order before and this seems the natural place to allow it.
