### ISSUE TITLE
"Existing data view" filter broken

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock-v8-Alpha-Issues#22]
Using the "Existing Data View" like so:

![image](https://user-images.githubusercontent.com/6932047/42294322-de05b414-7f94-11e8-9a39-aac98aa65847.png)

Results in an error being displayed on the resulting data view:

![image](https://user-images.githubusercontent.com/6932047/42294350-fe4190ea-7f94-11e8-90d2-209198d9b242.png)

and doesn't apply the filter. On the prealpha server, the resulting dataview (configuration shown in the first screen shot) results in a list of 53 people, while the original `Adult Members & Attendees` only has 29

Found the issue on my alpha server, verified on prealpha demo server.

**Comment by MikeDPeterson** [comment]
fixed with https://github.com/SparkDevNetwork/Rock/commit/cd2dcaf9d9f9f3b91c482f3d330ae924ad5c4be3
