### ISSUE TITLE
Welcome to Rock Content is Removed

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock-v8-Alpha-Issues#23]
I noticed that the v8 release notes state: _Updated the homepage, moving staff updates to the top of the page and removing the Welcome to Rock default content if it is unchanged._ but when I upgraded, the Welcome block was removed even though it had custom content differing from the default “Welcome to Rock”. 

So the release note seems to contradict the actual behavior. Can anyone else confirm?

**Comment by ethan-sparkdevnetwork** [comment]
We check if this exists in the content '%Administrators, add your organization&#39;s welcome message here.</p>%' assuming that if changes were made then this would no longer exist. So if your update left this intact then it would have been considered to be unchanged.

**Comment by JimMichael** [comment]
Hmm... My experience is different. My _Homepage Welcome_ block has (only) content like this
```<div class="alert alert-danger">
<h2>JIMROCK</h2>
<p>Database: 2018-05-23 4:00pm</p>
<p>Rock version: 7.4 (1.7.4.57)</p>
</div>``` yet when I upgrade to v8 that block is gone.

**Comment by ethan-sparkdevnetwork** [comment]
Migration does not consider use of versioning.

**Comment by ethan-sparkdevnetwork** [comment]
Updated migration 201806061732498_HomepageUpdates to check for HtmlContent rows for the welcome block not inserted by Rock migrations.
