### ISSUE TITLE
Attendance properties now read-only

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock-v8-Alpha-Issues#27]
A number of properties in the Attendance table were marked obsolete and now use the `=>` property to point to the new location where this value is stored. However, the `=>` property defines a `getter` only, not a `setter`. This is a breaking change for existing plugins.

Example, in v7 this would be valid:

```
var attendance = new Attendance();
attendance.LocationId = 123;
```

In v8, that is no longer valid and will cause an error.  Any properties changed in this way I think should be modified to have a full getter and setter to provide backwards compatibility to plugins and existing code.

**Comment by MikeDPeterson** [comment]
Fixed with https://github.com/SparkDevNetwork/Rock/commit/fefa9d507f892f25303f371879d5250946c82826

**Comment by MikeDPeterson** [comment]
@cabal95  I added a couple more fixes with https://github.com/SparkDevNetwork/Rock/commit/9c11ec09f9eaa39263cb392c7379dd9b63827df1
