### ISSUE TITLE
Schedule builder column alignment is off

### ISSUE THREAD

**Issue by lpeterson1** [SparkDevNetwork/Rock-v8-Alpha-Issues#28]
In the check-in configuration schedule builder the column alignment is off. It was beautiful in 7.4.

![screen shot 2018-07-12 at 10 50 03 am](https://user-images.githubusercontent.com/37701239/42649365-bf6737ca-85c6-11e8-894f-da5385eb81b1.png)

**Comment by garrettjohnson** [comment]
Fixed
![image](https://user-images.githubusercontent.com/374209/42658811-50133710-85db-11e8-8d37-378043e1026a.png)

**Comment by lpeterson1** [comment]
Thanks, @garrettjohnson. Really appreciate you.
