### ISSUE TITLE
Prealpha check-in site routes seem broken

### ISSUE THREAD

**Issue by lpeterson1** [SparkDevNetwork/Rock-v8-Alpha-Issues#29]
In /checkinmanager, the "home" button used to go to the Rock home page (V7); now it goes to the checkinmanager type selection page. There's no way out, other than manually entering a page number. /checkin behaves similarly: once you go to /checkin, prealpha.rocksolidchurchdemo.com goes directly to the phone lookup page. It seems a little unpredictable; sometimes quitting the browser makes it work and sometimes not. Opening a new browser tab does not seem to "fix" it.

**Comment by lpeterson1** [comment]
Hey Nick,

Sorry, I’m not a web guy. I was just going to http://prealpha.rocksolidchurchdemo.com/checkinmanager <http://prealpha.rocksolidchurchdemo.com/checkinmanager>, and once there the home button goes back to the type selection. I think Michael Garrison saw what I was seeing — maybe he might be able to tell you.

Let me know if you need anything else. Thanks for looking at it.


Lee

**Comment by nairdo** [comment]
Ah, yes that's the reason.  Thanks for letting me know.  It won't work in that environment with only one domain name ("prealpha.rocksolidchurchdemo.com").  Perhaps with more donations/funding we can buy another domain name for that demo site ;)

**Comment by lpeterson1** [comment]
Cool — glad to hear it. Wasn’t sure if it was a problem or not, but if that’s the way it was going to behave it would have made people nuts.

Thanks, man! Appreciate you.

Lee
