### ISSUE TITLE
Cannot select bottom-edge items in menu Rock Menu

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock-v8-Alpha-Issues#3]
If your internal portal Rock Menu reaches to the bottom of the screen, trying to select the bottom-most item causes the admin bar to pop up over top of the menu, which then dismisses the menu since the mouse leave event triggers.

![image](https://user-images.githubusercontent.com/1119863/41812312-8959e0b0-76d5-11e8-9609-4ecb55d0a77c.png)

**Comment by garrettjohnson** [comment]
Fixed via https://github.com/SparkDevNetwork/Rock/commit/d2dfcceba2cd60aeafed60fc55efed9b43adf4ff
