### ISSUE TITLE
Maximum Registrants cannot be set to 0

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock-v8-Alpha-Issues#30]
When editing a registration form, "Maximum Registrants" can no longer be left at the default 0 (which I understood to mean "unlimited".
![image](https://user-images.githubusercontent.com/6932047/42906498-2bd9b626-8a90-11e8-8e38-cbbe3d90104f.png)

**Comment by edmistj** [comment]
Looking for input on this. I get that this was the previous behavior, but it seems odd. Now blank means no upper limit. Does anyone see an issue with the new way other than a few admins having to re-learn the behavior?

**Comment by mikejed** [comment]
The reason I found this issue was, I went in to an existing registration and tried to edit one unrelated item. When I hit save, it wouldn't let it go through because the existing configuration was no longer valid.

Perhaps a migration to find these 0s and change them to blank instead, so that existing configurations don't appear to "break" would help ease the change...

**Comment by edmistj** [comment]
Unfortunately the model needs a value, it wasn't defined as int? and changing it could add a breaking change. We'll update the block to blank out if the value is 0.

**Comment by nairdo** [comment]
Fixed in https://github.com/SparkDevNetwork/Rock/commit/cd0b9240b507da1b4846790e98eeac190e05eeec.
