### ISSUE TITLE
Error The wait operation timed out - Trying to save after editing group type Display Options

### ISSUE THREAD

**Issue by nairdo** [SparkDevNetwork/Rock-v8-Alpha-Issues#31]
Would someone else please confirm their environment works fine or not?

**Release**: v8.0 alpha 2

**Environment**: 3Essentials plan: Windows 2016 VPS Pro 3G - Test VPS

**Comment by JimMichael** [comment]
I can't dupe on alpha1 (I edited a check-in group type and enabled Show In Group Lists and Show In Navigation and it saved fine.) Still working on getting reverted and installing alpha2

**Comment by nairdo** [comment]
@mikejed I think you have an alpha 2 test instance, right?  If so, can you try this?  Just edit and save a group type.

**Comment by mikejed** [comment]
@nairdo works fine for me on my alpha 2 production fork

**Comment by nairdo** [comment]
Thanks.  Must be something wrong with this test instance's database.  I'm rebuilding the db to see if the problem goes away.

**Comment by nairdo** [comment]
@mikejed Can you tell me if your database has "Is Read Committed Snapshot" set to "On" (look under (i) System info, Diagnostics) 
![image](https://user-images.githubusercontent.com/383807/43408944-661eace2-93d7-11e8-8bb7-bc3c33859cb1.png)

**Comment by JimMichael** [comment]
This sounds an awful lot like https://github.com/SparkDevNetwork/Rock-v8-Alpha-Issues/issues/13

**Comment by MikeDPeterson** [comment]
Fixed with https://github.com/SparkDevNetwork/Rock/commit/9464b82a4487d123f330c1c5cbda6c972690c699
