### ISSUE TITLE
Minor Font Awesome Label Issue

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock-v8-Alpha-Issues#32]
The Theme Styler in Admin | CMS Config | Themes | [theme] is showing the _Font Awesome Alternate Fonts_ label even when Pro is not installed, which looks confusing as you have no idea what the label is for.

Without FA Pro:
![image](https://user-images.githubusercontent.com/3903408/43027512-5c2eaff0-8c40-11e8-8c5a-4c06c5a5b93d.png)

With FA Pro:
![image](https://user-images.githubusercontent.com/3903408/43027520-631f0490-8c40-11e8-9270-269b9729e0e6.png)

**Comment by JimMichael** [comment]
Forgot to say this is on v8 alpha2

**Comment by shivambareria** [comment]
Fixed in https://github.com/SparkDevNetwork/Rock/commit/683b00804f574a202096930f10de73cec4431397 .
