### ISSUE TITLE
Theme colors get changed on upgrade?

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock-v8-Alpha-Issues#5]
The alpha instructions ask us to set a theme color (eg theme 1) and verify that it doesn't get changed by the upgrade. I changed Theme1 and Theme3 in my 7.4 instance to purple, which changed my header and buttons, etc to purple. After upgrade to v8, the header and buttons are now Rock orange.

**Comment by edmistj** [comment]
@JimMichael  this is as intended. The new v8 theme wipes out any overrides that were defined in the old theme as they won't be compatible in the new theme. In this unique case you can ignore that test.

We are considering though copying the custom overrides to a new location in case someone really needed access to them.
