### ISSUE TITLE
Dataview list is not sorted in Group Sync Settings

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock-v8-Alpha-Issues#6]
When setting up Group Sync Settings, the list of dataviews is no longer sorted properly... it looks like maybe it's sorting within each top-level dataview container, but not sorting the list as a whole. This is probably broken in other similar places but this is where I noticed it.

![image](https://user-images.githubusercontent.com/3903408/42001171-c02f6bcc-7a28-11e8-83e5-263c70738b96.png)

**Comment by ethan-sparkdevnetwork** [comment]
There was not any sort expression for the list on this page. I changed the DDL to a DataViewItemPicker so now we get a pretty, categorized, and sorted list.

Fixed in fc614426.

**Comment by ethan-sparkdevnetwork** [comment]
There was not any sort expression for the list on this page. I changed the DDL to a DataViewItemPicker so now we get a pretty, categorized, and sorted list.

Fixed in fc614426.
