### ISSUE TITLE
Several jobs haven't run since upgrade to v8

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock-v8-Alpha-Issues#7]
I noticed several new jobs have not run after the v8 upgrade, though they are active and scheduled (except for Process Adult Children). Is this normal? Also, the _Move data from Attendance table..._ job DID run, but hasn't deleted itself 24hr later.

![image](https://user-images.githubusercontent.com/3903408/42063647-4326d248-7af8-11e8-9234-a573363da9d5.png)

**Comment by JimMichael** [comment]
It looks like some of these ran this am: Calculate Person Signals, Migrate History Summary Data (but shows "3.3%"), and Process Group History all ran. The others still haven't run. The _Data Migrations for v8_ seems concerning as that implies something that should have run soon after upgrade... maybe?

**Comment by edmistj** [comment]
@JimMichael Do you think you could post an updated screenshot of the entire jobs list?

**Comment by JimMichael** [comment]
It looks like most jobs finally ran on their own (and you mentioned in my other issue that _Process Adult Children_ shouldn't be there), but the two stand-outs are the _Process BI Analytics_ and _Migrate History Summary Data_ which still error-out.

![image](https://user-images.githubusercontent.com/3903408/42174482-21ade550-7de8-11e8-8596-b3603d590e56.png)

**Comment by ethan-sparkdevnetwork** [comment]
We had a couple of migrations that changed the stored proc being used by these jobs. They were not in agreement. I have reconciled them and will include it in the next migration.
