### ISSUE TITLE
Process Adult Children Job Broken

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock-v8-Alpha-Issues#8]
I noticed the new _Process Adult Children_ job was disabled after upgrade to v8, and when I went to look at it to activate it, I got this error.
![image](https://user-images.githubusercontent.com/3903408/42063769-ded06e5c-7af8-11e8-8c6f-4ea830229c3b.png)

**Comment by edmistj** [comment]
This job was combined with the `Data Automation` job, but a migration needs to be made to remove it from the jobs list.

**Comment by shivambareria** [comment]
Fixed.
