### ISSUE TITLE
BI Analytics Job Fails

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock-v8-Alpha-Issues#9]
The BI analytics job that tried to run at 5am the day after I upgraded to v8 threw this error, with associated exceptions.

![image](https://user-images.githubusercontent.com/3903408/42097869-dc9e95c4-7b7e-11e8-832c-0c1c87c58b13.png)

**Comment by JimMichael** [comment]
Interesting... as part of working through the Process Street tests, it had me run the BI job, and this time (11hr later) it completed fine.

**Comment by MikeDPeterson** [comment]
Same issue as #7 (fixed with https://github.com/SparkDevNetwork/Rock/commit/0f7b6d25943b7108151853c773075ef7e545a688)
